graph LR
    subgraph RF[Reglas formales]
    A1[Forma lógica de las premisas] --> A2[Repertorio de reglas] --> A3[Derivación sintáctica]
    end
    subgraph MM[Modelos mentales]
    B1[Modelo de la situación descrita] --> B2[Conclusión tentativa] --> B3[Búsqueda de contraejemplos]
    end
