graph TD
    A["Desarrollo<br>Sexual Adolescente"]
    
    A -->|"Identidad Sexual"| B["Orientación y<br>Reconocimiento"]
    A --->|"Riesgos Asociados"| C["Conductas y<br>Consecuencias"]
    
    B -->|"Influencias"| B1["Biológicas,<br>Genéticas y Sociales"]
    
    C -->|"Infecciones"| C1["ETS (VPH,<br>VIH, Clamidia)"]
    C -->|"Maternidad/Paternidad"| C2["Embarazo<br>Adolescente"]
    
    C1 -->|"Prevención"| C3["Uso de<br>Condones"]
    C2 -->|"Prevención"| C3
    
    style B1 fill:#f9f2ec,stroke:#333
    style C1 fill:#f9f2ec,stroke:#333
    style C2 fill:#f9f2ec,stroke:#333