graph TD
    A["Éxito<br>Escolar"]
    
    A -->|"Factores Internos"| B["Motivación y<br>Autoeficacia"]
    A --->|"Factores Externos"| C["Contexto Social<br>y Familiar"]
    
    B -->|"Protección"| B1["Participación<br>Activa"]
    
    C -->|"Socioeconómico"| C1["Nivel<br>NSE Alto"]
    C -->|"Crianza"| C2["Estilo<br>Autoritativo"]
    
    A --->|"Riesgo"| D["Abandono<br>Escolar"]
    
    style B1 fill:#f9f2ec,stroke:#333
    style C1 fill:#f9f2ec,stroke:#333
    style C2 fill:#f9f2ec,stroke:#333
    style D fill:#f9f2ec,stroke:#333