graph TD
    A["Socialización<br>Familiar"]
    
    A -->|"Proceso Normativo"| B["Individuación y<br>Autonomía"]
    A --->|"Estilos Parentales"| C["Impacto en<br>el Desarrollo"]
    
    B -->|"Manifestación"| B1["Conflictos por<br>Límites Cotidianos"]
    
    C -->|"Óptimo"| C1["Crianza<br>Autoritativa"]
    C -->|"Nocivo"| C2["Control<br>Psicológico"]
    
    style B1 fill:#f9f2ec,stroke:#333
    style C1 fill:#f9f2ec,stroke:#333
    style C2 fill:#f9f2ec,stroke:#333