graph TD
    A["Desarrollo Hormonal<br>de la Pubertad"]
    
    A -->|"Etapa 1"| B["Adrenarquia<br>(7-8 años)"]
    A -->|"Etapa 2"| C["Gonadarquia<br>(Maduración Sexual)"]
    A --->|"Activador Biológico"| D["Acumulación de<br>Hormona Leptina"]
    
    B -->|"Glándulas"| B1["Suprarrenales"]
    B -->|"Hormona"| B2["Andrógenos (DHEA)"]
    
    C -->|"Femenino"| C1["Ovarios y<br>Estrógenos"]
    C -->|"Masculino"| C2["Testículos y<br>Testosterona"]
    
    D -->|"Señal al Cerebro"| D1["Suficiente Grasa<br>Para Reproducción"]
    
    style B2 fill:#f9f2ec,stroke:#333
    style C1 fill:#f9f2ec,stroke:#333
    style C2 fill:#f9f2ec,stroke:#333
    style D1 fill:#f9f2ec,stroke:#333