graph TD
    A["Pensamiento<br>Formal"]
    
    A -->|"Diferencia"| B["Forma vs.<br>Contenido"]
    A --->|"Logro"| C["Pensamiento<br>Hipotético-Deductivo"]
    
    B -->|"Permite"| D["La Combinatoria<br>Sistemática"]
    D -->|"Aplica a"| D1["Combinación<br>de Objetos"]
    D -->|"Aplica a"| D2["Combinación<br>de Proposiciones"]
    
    D1 ~~~ D2
    
    style D1 fill:#f9f2ec,stroke:#333
    style D2 fill:#f9f2ec,stroke:#333