graph TD
    A["Influencias sobre<br>el Desarrollo"] --> B["Influencias<br>Normativas"]
    B --> C["Determinadas por la Edad<br>(Menopausia, Jubilación)"]
    B --> D["Determinadas Históricamente<br>(Guerras, Crisis Económicas)"]
    A --> E["Influencias<br>No Normativas"]
    E --> F["Eventos Atípicos<br>(Accidentes, Lotería)"]
    E --> G["Eventos Típicos a<br>Tiempos Atípicos<br>(Viudez a los 20s)"]
    A --> H["Enfoque Bioecológico<br>(Bronfenbrenner)"]
    H --> I["Microsistema<br>(Interacción directa)"]
    H --> J["Mesosistema<br>(Conexión de microsistemas)"]
    H --> K["Exosistema<br>(Influencias indirectas)"]
    H --> L["Macrosistema<br>(Ideología y Cultura)"]
    H --> M["Cronosistema<br>(Dimensión temporal)"]