graph TD
    A["Factores de<br>Mantenimiento"]
    
    A -->|"Sustancias"| B["Tabaco y<br>Alcohol"]
    A -->|"Psicológico"| C["Manejo del<br>Estrés"]
    A --->|"Fisiológico"| D["Dieta y<br>Ejercicio"]
    
    B -->|"Riesgo"| B1["Cáncer y<br>Cardiopatías"]
    
    C -->|"Afrontamiento"| C1["Locus de<br>Control Interno"]
    C -->|"Impacto"| C2["Deterioro<br>Inmunológico"]
    
    D -->|"Nutrición"| D1["Control IMC<br>y Colesterol"]
    D -->|"Actividad"| D2["Mejora reserva<br>cardiorrespiratoria"]
    
    style B1 fill:#f9f2ec,stroke:#333
    style C1 fill:#f9f2ec,stroke:#333
    style D1 fill:#f9f2ec,stroke:#333
    style D2 fill:#f9f2ec,stroke:#333