graph TD
    A["Sistemas<br>Reproductivos"]
    
    A -->|"Femenino"| B["Menopausia"]
    A --->|"Masculino"| C["Andropausia"]
    
    B -->|"Hormonas"| B1["Caída<br>de Estrógeno"]
    B -->|"Síntomas"| B2["Bochornos<br>y Resequedad"]
    
    C -->|"Hormonas"| C1["Menos<br>Testosterona"]
    C -->|"Fisiología"| C2["Disfunción<br>Eréctil"]
    
    style B1 fill:#f9f2ec,stroke:#333
    style B2 fill:#f9f2ec,stroke:#333
    style C1 fill:#f9f2ec,stroke:#333
    style C2 fill:#f9f2ec,stroke:#333