graph TD
    A["Apariencia<br>Física"]
    
    A -->|"Piel"| B["Menos<br>Elasticidad"]
    A --->|"Composición"| C["Músculo<br>por Grasa"]
    A --->|"Estructura"| D["Reducción<br>de Estatura"]
    
    B -->|"Impacto"| B1["Arrugas<br>y Manchas"]
    C -->|"Impacto"| C1["Aumento<br>de Peso"]
    D -->|"Impacto"| D1["Atrofia<br>Discal"]
    
    style B1 fill:#f9f2ec,stroke:#333
    style C1 fill:#f9f2ec,stroke:#333
    style D1 fill:#f9f2ec,stroke:#333