graph TD
    A["Cáncer de<br>Próstata"]
    
    A -->|"Detección"| B["Pruebas de<br>Tamizaje"]
    A --->|"Tratamiento"| C["Opciones<br>Médicas"]
    
    B -->|"Sanguínea"| B1["Prueba PSA<br>(Antígeno)"]
    B -->|"Física"| B2["Examen DRE<br>(Tacto Rectal)"]
    
    C -->|"Extirpación"| C1["Cirugía<br>(Prostatectomía)"]
    C -->|"Bloqueo"| C2["Terapia<br>Hormonal"]
    
    style B1 fill:#f9f2ec,stroke:#333
    style B2 fill:#f9f2ec,stroke:#333
    style C1 fill:#f9f2ec,stroke:#333
    style C2 fill:#f9f2ec,stroke:#333