graph TD
    A[Neurosis narcisistas y melancolia: Freud] --> B[Clinica de los bordes]
    B --> C[Nombre del Padre eficaz]
    C --> D[Funcion paterna: limite eficaz pero metafora fallida]
    D --> E[Fracaso de la funcion falica]
    E --> F[Fracaso del fantasma detenido en el tiempo narcisista]
    F --> G[Angustia masiva y fragilidad del ser]
    F --> H[Identificaciones masificantes]
    G --> I[Cortocircuitos del acto: acting out y pasaje al acto]
    F --> J[Anorexia y bulimia veras]
    E --> K[Holofrase: fenomenos psicosomaticos]
    F --> L[Adicciones: sintoma pret a porter]
    F --> M[Locuras: delirium y duelo]
    F --> N[Melancolizaciones y depresiones]
