graph TD
    A["Envejecimiento<br>Fisiológico"]
    
    A -->|"Teorías Genéticas"| B["Senectud Programada<br>y Límite Celular"]
    A --->|"Teorías de Error"| C["Radicales Libres<br>y Desgaste"]
    
    A -->|"Resultados"| D["Cambios<br>Sensoriomotores"]
    A --->|"Prevención"| E["Hábitos de Salud<br>y Estilo de Vida"]

    D -->|"Sensorial"| D1["Presbicia y<br>Presbiacusia"]
    D -->|"Motor"| D2["Atrofia y Menor<br>Tiempo Reacción"]
    
    E -->|"Factores Negativos"| E1["Tabaco, Estrés<br>y Pobreza"]
    E -->|"Factores Protectores"| E2["Ejercicio, Dieta y<br>Redes Sociales"]

    style B fill:#f9f2ec,stroke:#333
    style C fill:#f9f2ec,stroke:#333
    style D1 fill:#f9f2ec,stroke:#333
    style D2 fill:#f9f2ec,stroke:#333
    style E1 fill:#f9f2ec,stroke:#333
    style E2 fill:#f9f2ec,stroke:#333